ALTER TABLE InfoAboutEmployers ADD
	IAM_NOTES NVARCHAR(3000)
GO
exec sp_addextendedproperty N'MS_Description', N'Piezîme kas tiks drukâtas veidlapâ', N'user', N'dbo', N'table', N'InfoAboutEmployers', N'column', N'IAM_NOTES'
GO
ALTER TABLE CodeCheck ADD
	CCH_STATUS TINYINT
GO
exec sp_addextendedproperty N'MS_Description', N'Statuss 1 - Jauns, 2 - izpildîts', N'user', N'dbo', N'table', N'CodeCheck', N'column', N'CCH_STATUS'
GO
UPDATE StateDutyServices SET SDS_NOT_FROM_TAXPAYER=0 where SDS_NOT_FROM_TAXPAYER IS NULL
GO
ALTER TABLE Gambles ALTER COLUMN GMB_OWNER_CODE NVARCHAR(11) NULL
GO
ALTER TABLE Gambles ALTER COLUMN GMB_OWNER_NAME NVARCHAR(250) NULL
GO
ALTER TABLE Gambles ALTER COLUMN GMB_OWNER_ADDRESS NVARCHAR(250) NULL
GO
ALTER TABLE Gambles ALTER COLUMN GMB_HAS_LICENCE BIT NULL
GO
ALTER TABLE Gambles ALTER COLUMN GMB_HAS_RULES BIT NULL
GO
ALTER TABLE Gambles ALTER COLUMN GMB_HAS_ACT BIT NULL
GO
ALTER TABLE Gambles ALTER COLUMN GMB_AGE_CHECK BIT NULL
GO
ALTER TABLE TimberStackMeasures ALTER COLUMN TSM_PLACE TINYINT NULL
GO
ALTER TABLE DataCompareDetails ALTER COLUMN DCD_PARTNER_CODE NVARCHAR(11) NULL
GO
ALTER TABLE DataCompareDetails ALTER COLUMN DCD_PARTNER_NAME NVARCHAR(250) NULL
GO
ALTER TABLE DataCompareDetails ALTER COLUMN DCD_DEAL_DATE Datetime NULL
GO
ALTER TABLE DataCompareDetails ALTER COLUMN DSD_NUMBER TINYINT NULL
GO
ALTER TABLE DataCompareDetails ALTER COLUMN DCD_DEAL_SUM decimal(18,2) NULL
GO
ALTER TABLE DataCompareDetails ALTER COLUMN DCD_DOC_TYPE_ID uniqueidentifier NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_PERIOD_FROM Datetime NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_PERIOD_UNTIL Datetime NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_COUNT INT NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_REMAINDER INT NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_REPORT INT NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_USED_REPORT INT NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_ANNULLED_REPORT INT NULL
GO
ALTER TABLE MandatoryFormDetails ALTER COLUMN MFD_REMAINDER_END INT NULL
GO
ALTER TABLE RealEstate ALTER COLUMN REP_PERIOD_FROM Datetime NULL
GO
ALTER TABLE RealEstate ALTER COLUMN REP_PERIOD_UNTIL Datetime NULL
GO
ALTER TABLE RealEstate ALTER COLUMN REP_PAYER_COUNT_DATE Datetime NULL
GO
ALTER TABLE RealEstate ALTER COLUMN REP_SUM_CALCULATED decimal(18,2) NULL
GO
ALTER TABLE RealEstate ALTER COLUMN REP_SUM_COLLECTED decimal(18,2) NULL
GO
ALTER TABLE TimberRegisterResponsibles ALTER COLUMN TRR_NAME NVARCHAR(100) NULL
GO
ALTER TABLE CMCaseViolations ALTER COLUMN CVI_THEME_ID uniqueidentifier NULL
GO
ALTER TABLE SrsNumberRequisites ALTER COLUMN SRR_REQUISITE_ID uniqueidentifier NULL
GO
ALTER TABLE CashOperationMoney ALTER COLUMN COU_MONEY_UNIT_ID TINYINT NULL
GO
ALTER TABLE TaxpayerInform ALTER COLUMN TPI_INFORM_ID uniqueidentifier NULL
GO
ALTER TABLE ExternalPersons ALTER COLUMN EXP_ORGANIZATION_ID uniqueidentifier NULL
GO
UPDATE _SysParameters SET PRM_VALUE = '32' WHERE PRM_NAME LIKE ('VERSION_%_DB')    