ALTER TABLE TaxpayerMembers ALTER COLUMN TPM_CODE nvarchar(11) NULL
GO
ALTER TABLE TaxpayerMembers ALTER COLUMN TPM_NAME nvarchar(250) NULL
GO
ALTER TABLE InvitationDocuments ALTER COLUMN IND_DOCUMENT nvarchar(250) NULL
GO
ALTER TABLE ConstructionContractors ALTER COLUMN COC_NAME nvarchar(250) NULL
GO
ALTER TABLE ConstructionContractors ALTER COLUMN COC_CODE nvarchar(11) NULL
GO
ALTER TABLE CashDealDetails ALTER COLUMN CDD_PERIOD_FROM datetime NULL
GO
ALTER TABLE CashDealDetails ALTER COLUMN CDD_PERIOD_UNTIL datetime NULL
GO
ALTER TABLE CashDealDetails ALTER COLUMN CDD_TAXPAYER_CODE nvarchar(11) NULL
GO
ALTER TABLE CashDealDetails ALTER COLUMN CDD_TAXPAYER_NAME nvarchar(250) NULL
GO
ALTER TABLE WWDocumentsRequisites ALTER COLUMN WDR_REQUISITE_ID uniqueidentifier NULL
GO
ALTER TABLE Classifiers ALTER COLUMN CLS_NAME nvarchar(500) NULL
GO
UPDATE InfoAboutEmployers SET IAM_NOTES= NULL
GO
ALTER TABLE InfoAboutEmployers ALTER COLUMN IAM_NOTES nvarchar(2000) NULL
GO
ALTER TABLE InfoAboutEmployers ALTER COLUMN IAM_VOLUME_OF_PRODUCTION nvarchar(1800) NULL
GO
UPDATE _SysParameters SET PRM_VALUE = '33' WHERE PRM_NAME LIKE ('VERSION_%_DB')   